src/Entity/Frame.php
<?php

namespace App\Entity;

use App\Repository\FrameRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FrameRepository::class)]
#[ORM\UniqueConstraint(
    name: 'player_round_idx',
    columns: ['player_id', 'round']
)]
class Frame
{
    const STATE_NEW = 'new';
    const STATE_SECOND_ROLL = 'second_roll';
    const STATE_THIRD_ROLL = 'third_roll';
    const STATE_WAIT_SCORE = 'wait_score';
    const STATE_DONE = 'done';

    const PINS_PER_FRAME = 10;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $round = null;

    #[ORM\Column(length: 255, options: ['default' => self::STATE_NEW])]
    private ?string $state = self::STATE_NEW;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $score_wait = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $roll_1 = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $roll_2 = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $roll_3 = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $score = 0;

    #[ORM\ManyToOne(inversedBy: 'frames')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Player $player = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRound(): ?int
    {
        return $this->round;
    }

    public function setRound(int $round): self
    {
        $this->round = $round;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getScoreWait(): ?int
    {
        return $this->score_wait;
    }

    public function setScoreWait(int $score_wait): self
    {
        $this->score_wait = $score_wait;

        return $this;
    }

    public function getRoll1(): ?int
    {
        return $this->roll_1;
    }

    public function setRoll1(int $roll_1): self
    {
        $this->roll_1 = $roll_1;
        $this->score += $roll_1;

        return $this;
    }

    public function getRoll2(): ?int
    {
        return $this->roll_2;
    }

    public function setRoll2(int $roll_2): self
    {
        $this->roll_2 = $roll_2;
        $this->score += $roll_2;

        return $this;
    }


    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getPlayer(): ?Player
    {
        return $this->player;
    }

    public function setPlayer(?Player $player): self
    {
        $this->player = $player;

        return $this;
    }

    public function getRoll3(): ?int
    {
        return $this->roll_3;
    }

    public function setRoll3(int $roll_3): self
    {
        $this->roll_3 = $roll_3;
        $this->score += $roll_3;

        // third roll also propagates its score to frame's first roll
        $this->score += $roll_3;

        return $this;
    }
}

src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GameRepository::class)]
#[UniqueEntity('reference')]
#[ORM\HasLifecycleCallbacks]
class Game
{
    const STATE_NEW = 'new';
    const STATE_PLAYING = 'playing';
    const STATE_PLAYERS_FINISHED = 'players_finished';
    const STATE_FINISHED = 'finished';


    public const FRAMES_PER_GAME = 10;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private ?string $reference = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Player::class, orphanRemoval: true)]
    #[ORM\OrderBy(value: ["position" => "ASC"])]
    private Collection $players;

    #[ORM\Column(length: 255, options: ['default' => self::STATE_NEW])]
    private ?string $state = self::STATE_NEW;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Player $WinnerPlayer = null;

    public function __construct()
    {
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players->add($player);
            $player->setGame($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getGame() === $this) {
                $player->setGame(null);
            }
        }

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    #[ORM\PrePersist]
    public function setReferenceValue(): void
    {
        $this->reference = bin2hex(random_bytes(16));
    }

    public function getWinnerPlayer(): ?Player
    {
        return $this->WinnerPlayer;
    }

    public function setWinnerPlayer(?Player $WinnerPlayer): self
    {
        $this->WinnerPlayer = $WinnerPlayer;

        return $this;
    }
}

src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
#[ORM\UniqueConstraint(
    name: 'game_position_idx',
    columns: ['game_id', 'position']
)]
#[ORM\HasLifecycleCallbacks]
class Player
{
    const STATE_WAITING = 'waiting';
    const STATE_PLAYING = 'playing';
    const STATE_FINISHED = 'finished';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255, options: ['default' => self::STATE_WAITING])]
    private ?string $state = self::STATE_WAITING;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $final_score = 0;

    #[ORM\Column]
    private ?int $position = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game = null;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Frame::class, orphanRemoval: true)]
    #[ORM\OrderBy(value: ["round" => "ASC"])]
    private Collection $frames;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $last_round = 0;

    public function __construct()
    {
        $this->frames = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getFinalScore(): ?int
    {
        return $this->final_score;
    }

    public function setFinalScore(int $final_score): self
    {
        $this->final_score = $final_score;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    /**
     * @return Collection<int, Frame>
     */
    public function getFrames(): Collection
    {
        return $this->frames;
    }

    public function addFrame(Frame $frame): self
    {
        if (!$this->frames->contains($frame)) {
            $this->frames->add($frame);
            $frame->setPlayer($this);
        }

        return $this;
    }

    public function removeFrame(Frame $frame): self
    {
        if ($this->frames->removeElement($frame)) {
            // set the owning side to null (unless already changed)
            if ($frame->getPlayer() === $this) {
                $frame->setPlayer(null);
            }
        }

        return $this;
    }

    #[ORM\PrePersist]
    public function setPositionValue()
    {
        $this->position = $this->getGame()->getPlayers()->count();
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }

    public function getLastRound(): ?int
    {
        return $this->last_round;
    }

    public function setLastRound(int $last_round): self
    {
        $this->last_round = $last_round;

        return $this;
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Frame;
use App\Entity\Game;
use App\Entity\Player;
use App\Form\FrameRollFormType;
use App\Form\NewGameFormType;
use App\Form\NewPlayerFormType;
use App\Message\FrameMessage;
use App\Message\GameMessage;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class GameController extends AbstractController
{

    public function __construct(
        private EntityManagerInterface $entityManager,
        private MessageBusInterface    $bus,
    )
    {
    }

    #[Route('/', name: 'homepage')]
    public function create(
        Request $request,
    ): Response
    {
        $game = new Game();

        $form = $this->createForm(NewGameFormType::class, $game);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($game);
            $this->entityManager->flush();

            return $this->redirectToRoute('configure_game', ['reference' => $game->getReference()]);
        }

        return $this->render('game/create.html.twig', [
            'game' => $game,
            'game_form' => $form,
        ]);
    }


    #[Route('/setup/{reference}', name: 'configure_game')]
    public function configure(
        Request $request,
        Game    $game,
    ): Response
    {
        if ($game->getState() != Game::STATE_NEW) {
            return $this->redirectToRoute('game_show', ['reference' => $game->getReference()]);
        }

        $player = new Player();
        $form = $this->createForm(NewPlayerFormType::class, $player);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->get('addPlayer')->isClicked() && $form->isValid()) {
                $player->setGame($game);
                $this->entityManager->persist($game);

                $game->addPlayer($player);
                $this->entityManager->persist($player);
                $this->entityManager->flush();

                $player = new Player();
                $form = $this->createForm(NewPlayerFormType::class, $player);

            } else if ($form->get('startGame')->isClicked()) {
                if ($game->getPlayers()->count() > 0) {
                    $this->bus->dispatch(new GameMessage($game->getId()));
                    return $this->redirectToRoute('game_show', ['reference' => $game->getReference()]);
                } else {
                    $form->addError(new FormError("Game must have at least one player to be started"));
                }
            }
        }

        return $this->render('game/configure.html.twig', [
            'game' => $game,
            'game_form' => $form,
        ]);
    }

    #[Route('/show/{reference}', name: 'game_show')]
    public function show(
        Request $request,
        Game    $game,
    ): Response
    {
        if ($game->getState() == Game::STATE_NEW) {
            return $this->redirectToRoute('configure_game', ['reference' => $game->getReference()]);
        }

        // find player in playing state
        $players_playing = $game->getPlayers()->filter(function (Player $player) {
            return $player->getState() == 'playing';
        })->first();

        if (!empty($players_playing)) {
            // find frame alive
            $frame_alive = $players_playing->getFrames()->filter(function (Frame $frame) {
                return $frame->getState() == 'new' || $frame->getState() == 'second_roll' || $frame->getState() == 'third_roll';
            })->first();

            $form = $this->createForm(FrameRollFormType::class, $frame_alive);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $rolled_pins = $form['roll']->getData();
                assert($frame_alive->getScore() + $rolled_pins < Frame::PINS_PER_FRAME);

                $this->bus->dispatch(new FrameMessage($frame_alive->getId(), $rolled_pins));
            }
        } else {
            $form = null;
            $frame_alive = null;
        }

        return $this->render('game/show.html.twig', [
            'game' => $game,
            'frame' => $frame_alive,
            'frame_form' => $form,
        ]);
    }
}

templates/game/configure.html.twig
{% extends 'base.html.twig' %}

{% block title %}Let's add players to the game!{% endblock %}

{% block body %}

    <div class="row mt-3">
        {% if form_errors(game_form) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(game_form) }}
                </div>
        {% endif %}
        <div class="card col-8">
            <div class="card-body">
                <h3 class="card-title fw-bold">{{ game.name|upper }}</h3>
                <div class="card-text">
                    <h5 class="card-title">Current players</h5>
                    <ul class="list-group">
                        {% if game.players|length > 0 %}
                            {% for player in game.players %}
                                <li class="list-group-item list-group-item-action">{{ player.name }}</li>
                            {% endfor %}
                        {% else %}
                            <li class="list-group-item" disabled>There are no players yet... Add one!</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="card col-4">
            <div class="card-body">
                <h3 class="card-title">Setup game</h3>

                <div class="card-text">
                    {{ form_start(game_form) }}
                    {{ form_row(game_form.name, {label: 'New Player Name'}) }}
                    <div class="btn-group" role="group">
                    {{ form_widget(game_form.addPlayer, {label: 'Add Player'}) }}
                    {{ form_widget(game_form.startGame, {label: 'Start Game', attr: {class: 'btn-success'}}) }}
                    </div>
                    {{ form_end(game_form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/game/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new Bowling Game!{% endblock %}

{% block body %}

<div class="row">
    <div class="pt-3 offset-sm-3 offset-lg-4 col-12 col-sm-6 col-lg-4">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Yupop Bowling</h2>
                <h6 class="card-title">Start a new game!</h6>

                <div class="card-text">
                    {{ form_start(game_form) }}
                    {{ form_row(game_form.name, {label: false, attr: {placeholder: 'Game name'}}) }}
                    {{ form_end(game_form) }}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/game_show.js') }}"></script>
{% endblock %}

{% block title %}Playing game {{ game.name }}!{% endblock %}

{% block body %}
    {% set max_throw = constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
    {% set actual_player = '' %}
    <div class="row">
        <div class="container col-12 bg-light bg-opacity-75 p-3 rounded mt-1">
            <div class="row">
                <h1 class="fw-bold">{{ game.name|upper }}</h1>
            </div>
            <div class="row mt-3">
                <div class="col-1 text-secondary text-nowrap">
                    &nbsp;
                </div>
                {% for i in range(1, constant('App\\Entity\\Game::FRAMES_PER_GAME')) %}
                    <div class="col-1 text-secondary">
                        {{ i }}
                    </div>
                {% endfor %}
                <div class="col-1 text-secondary">
                    &nbsp;
                </div>

            </div>
            {% for player in game.players %}
                <div class="row mt-3 border-bottom border-secondary {{ player.state == "playing" ? "bg-warning" }}">
                    <div class="col-1 text-truncate align-middle">
                        {{ player.name|capitalize }}
                    </div>
                    {% for frame in player.frames %}
                        {% if player.state == 'playing' and frame.state in ["second_roll"] %}
                            {% set max_throw = constant('App\\Entity\\Frame::PINS_PER_FRAME')-frame.roll1 %}
                        {% endif %}

                        {{ _self.render_frame(player, frame) }}
                    {% endfor %}

                    {% if player.frames|length < constant('App\\Entity\\Game::FRAMES_PER_GAME') %}
                        {% for i in range(player.frames|length+1, constant('App\\Entity\\Game::FRAMES_PER_GAME')) %}
                            {{ _self.render_empty_frame(i) }}
                        {% endfor %}
                    {% endif %}
                    <div class="col-1 fw-bold">
                        {{ player.finalScore }}
                    </div>
                </div>
            {% endfor %}

        </div>
        {% if game.state == "playing" %}
            <div class="card col-12">
                <div class="card-body">
                    <h5 class="card-title">Roll the ball!</h5>

                    <div class="card-text">
                        {{ form_start(frame_form) }}
                        <div id="frame_roll_buttons" class="btn-group" role="group">
                            {% for val in range(0,constant('App\\Entity\\Frame::PINS_PER_FRAME')) %}
                                {{ _self.draw_roll_button(frame_form, val, max_throw) }}
                            {% endfor %}
                        </div>
                        <input type="hidden" id="frame_roll_max_value" value="{{ max_throw }}"/>
                        {{ form_widget(frame_form.roll, {'type': 'hidden'}) }}
                        {{ form_widget(frame_form._token, {'type': 'hidden'}) }}
                        {{ form_end(frame_form, { render_rest: false}) }}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="card col-12">
                <div class="card-body">
                    <h5 class="card-title">The game has finished!</h5>

                    <div class="card-text">
                        The winner is <b>{{ game.winnerPlayer.name }}</b> with <b>{{ game.winnerPlayer.finalScore }}
                            points</b>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% macro render_frame(player, frame) %}
    <div class="col-1 m-0 p-0">
        <div class="row g-0">
            {% if frame.round < constant('App\\Entity\\Game::FRAMES_PER_GAME') %}
                <div class="col-6 border border-secondary border-1 text-center">
                    {{ _self.draw_roll_1(frame) }}
                </div>
                <div class="col-6 border border-secondary border-1">
                    {{ _self.draw_roll_2(frame) }}
                </div>
            {% else %}
                <div class="col-4 border border-secondary border-1 text-center">
                    {{ _self.draw_roll_1(frame) }}
                </div>
                <div class="col-4 border border-secondary border-1">
                    {{ _self.draw_roll_2(frame) }}
                </div>
                <div class="col-4 border border-secondary border-1">
                    {{ _self.draw_roll_bonus(frame) }}
                </div>
            {% endif %}
        </div>
        <div class="row border border-secondary border-1 g-0">
            <div class="col-12">
                {{ _self.draw_frame_score(player, frame) }}
            </div>
        </div>
    </div>
{% endmacro %}

{% macro render_empty_frame(round) %}
    <div class="col-1 m-0 p-0">
        <div class="row g-0">
            {% if round < constant('App\\Entity\\Game::FRAMES_PER_GAME') %}
                <div class="col-6 border border-secondary border-1 text-center">
                    &nbsp;
                </div>
                <div class="col-6 border border-secondary border-1">
                    &nbsp;
                </div>
            {% else %}
                <div class="col-4 border border-secondary border-1 text-center">
                    &nbsp;
                </div>
                <div class="col-4 border border-secondary border-1">
                    &nbsp;
                </div>
                <div class="col-4 border border-secondary border-1">
                    &nbsp;
                </div>
            {% endif %}
        </div>
        <div class="row border border-secondary border-1 g-0">
            <div class="col-12">
                &nbsp;
            </div>
        </div>
    </div>
{% endmacro %}

{% macro draw_roll_1(frame) %}
    {% if frame.state in ['new'] %}
        &nbsp;
    {% else %}
        {% if frame.roll1 == constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
            X
        {% elseif frame.roll1 == 0 %}
            -
        {% else %}
            {{ frame.roll1 }}
        {% endif %}
    {% endif %}
{% endmacro %}

{% macro draw_roll_2(frame) %}
    {% if frame.state in ['new','second_roll'] or frame.roll1 == constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
        &nbsp;
    {% else %}
        {% if frame.roll1+frame.roll2 == constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
            /
        {% elseif frame.roll2 == 0 %}
            -
        {% else %}
            {{ frame.roll2 }}
        {% endif %}
    {% endif %}
{% endmacro %}

{% macro draw_roll_bonus(frame) %}
    {% if frame.state in ['new','second_roll','third_roll'] or frame.roll1+frame.roll2 < constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
        &nbsp;
    {% elseif frame.roll3 == constant('App\\Entity\\Frame::PINS_PER_FRAME') %}
        X
    {% else %}
        {{ frame.roll3 }}
    {% endif %}
{% endmacro %}

{% macro draw_frame_score(player, frame) %}
    {% if frame.state == "done" %}
        {% set score = 0 %}
        {% for player_frame in player.frames|filter(f => f.round <= frame.round and f.state == "done") %}
            {% set score = score + player_frame.score %}
        {% endfor %}

        {{ score }}
    {% else %}
        &nbsp;
    {% endif %}
{% endmacro %}

{% macro draw_roll_button(form, value, max_value) %}
    {% set attr = '' %}
    {% if value > max_value %}
        {% set attr = 'disabled' %}
    {% endif %}
    <button name="roll{{ value }}" type="button" class="btn btn-primary" {{ attr }} data-input-value="{{ value }}"
            data-input-target="{{ form.roll.vars.id }}">{{ value }}</button>
{% endmacro %}